### ISSUE TITLE
MinIO web interface no longer accessible

### ISSUE THREAD

**Issue by mbennett-uoe** [esmero/archipelago-deployment#118] opened 2021-08-11 14:53 UTC
Since [RELEASE.2021-07-08T01-15-01Z](https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z), MinIO has removed the builtin MinIO browser in favour of integrating their MinIO Console product and providing an automatic redirect from the MinIO API.

Therefore deployments of Archipelago built after this version was released will pull a `minio/minio:latest` image that contains this breaking change, and the esmero-minio container will not be accessible via the web browser interface.

This is because the service will attempt to issue a redirect to the new Console port, which is obviously unavailable outside the container (although API requests on port 9000 will still work, as these don't get redirected, meaning this problem will be "invisible" to existing deployments that just update the image).

As far as I can see, there are two options for fixing:
1) Pin the `docker-compose.yml` files to a version of MinIO from before this breaking change, rather than `latest`
2) Update the MinIO configuration to work with the new Console access

Happily the second of these is very simple, so I'll send a PR shortly in case that's the route you wish to go down.

Thanks for all the great work on Archipelago so far - really excited to be trying out RC2 and hoping we will make a magical set of islands a permanent part of our DL setup :)

**Comment by mbennett-uoe** [comment] 2021-08-11 14:54
My apologies, somehow I missed ticket #108 which was already open for this issue!

**Comment by aksm** [comment] 2021-10-28 18:41
Duplicate of #108

**Closed as completed by aksm** 2021-10-28 18:41 UTC
